Webapps-Mappe1/Controllers/AdminController.cs
using System;
using System.Web.Mvc;

using Webapps_Mappe1.Model;
using Webapps_Mappe1.BLL;
using System.IO;

namespace Webapps_Mappe1.Controllers
{
    public class AdminController : Controller
    {
        StationBLL stationBLL;
        DepartureBLL departureBLL;
        PriceBLL priceBLL;
        AdminBLL userBLL;

        public AdminController()
        {
            stationBLL = new StationBLL();
            departureBLL = new DepartureBLL();
            priceBLL = new PriceBLL();
            userBLL = new AdminBLL();
        }

        public AdminController(PriceBLL priceBLLStub)
        {
            priceBLL = priceBLLStub;
        }

        public ActionResult Index()
        {
            if (userBLL.CheckAdminExists())
            {
                userBLL.createAdmin();
                Session["SignIn"] = false;
            }


            if (Session["SignIn"] == null || !(bool)Session["SignIn"])
            {
                Session["SignIn"] = false;
                ViewBag.Signedin = false;
            }
            else
            {
                ViewBag.Signedin = (bool)Session["SignIn"];
                return RedirectToAction("AdminPage");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Index(Admin inUser)
        {
            DBUser foundUser = userBLL.UserInDB(inUser);
            if (foundUser != null)
            {
                Session["SignIn"] = true;
                ViewBag.Signedin = inUser.Name;
                Session["username"] = inUser.Name;
                return RedirectToAction("AdminPage");
            }
            else
            {
                Session["SignIn"] = false;
                ViewBag.Signedin = "Else";
                Session["username"] = "Automatisk";
                return View();
            }
        }


        public ActionResult AdminPage()
        {
            if (Session["SignIn"] != null)
            {
                bool SignIn = (bool)Session["SignIn"];
                if (SignIn)
                {
                    return View();
                }
            }
            return RedirectToAction("Index");
        }


        protected override void OnException(ExceptionContext filterContext)
        {
            using (StreamWriter w = System.IO.File.AppendText(Server.MapPath(@"error.log")))
            {
                Log(filterContext.Exception.ToString(), w);
            }
            base.OnException(filterContext);
        }

        private void Log(string logMessage, TextWriter w)
        {
            w.WriteLine($"AdminController");
            w.Write("\r\nLog Entry: ");
            w.WriteLine($"{DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}\r\n");
            w.WriteLine($" {logMessage}\r\n");
            w.WriteLine("-----------------------------");
        }
    }
}

Webapps-Mappe1/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webapps_Mappe1.BLL;
using Webapps_Mappe1.Model;

namespace Webapps_Mappe1.Controllers
{
    public class TicketController : Controller
    {
        private readonly StationBLL stationBLL;
        private readonly DepartureBLL departureBLL;

        TicketBLL ticketBLL;

        public TicketController()
        {
            ticketBLL = new TicketBLL();
            stationBLL = new StationBLL();
            departureBLL = new DepartureBLL();
    }

        public TicketController(TicketBLL ticketBLLStub)
        {
            ticketBLL = ticketBLLStub;

        }
        public ActionResult Index()
        {

           /* StationBLL stationBLL = new StationBLL();

            if(stationBLL.CheckStationsNotExists())
            {
                CreateStations();
                CreateDepartures();
                CreatePrices();
            }*/
            return View();
        }

        [HttpPost]
        public ActionResult Index(Ticket postTicket)
        {
            if (ModelState.IsValid)
            {
                if (ticketBLL.createNewTicket(postTicket))
                {
                    return RedirectToAction("ShowTickets");
                }
            }
            return View();
        }
        
        public ActionResult ShowTickets()
        {
            List<DBTicket> tickets = ticketBLL.GetTickets();
            return View(tickets);
        }

        public ActionResult Details(int id)
        {
            DBTicket ticket = ticketBLL.findTicket(id);
            return View(ticket);
        }
        
        public JsonResult GetStationsJson()
        {
            JsonResult output = Json(stationBLL.GetAllStations(), JsonRequestBehavior.AllowGet);
            return output;
        }

        public JsonResult GetDepartureJson(DepartureModel departure)
        {
            JsonResult output = Json(departureBLL.GetDepartures(departure), JsonRequestBehavior.AllowGet);
            return output;
        }

       private void CreateDepartures()
        {
            DepartureBLL departureBLL = new DepartureBLL();
            departureBLL.CreateDepartures();
        }


        
       /* private void CreateStations()

        {
            StationBLL stationBLL = new StationBLL();
            stationBLL.CreateStations();
        }
        */
        private void CreatePrices()
        {
            PriceBLL priceBLL = new PriceBLL();
            priceBLL.CreatePrices();
        }
        
        public ActionResult Reset()
        {
            AdminBLL userBLL = new AdminBLL();
            userBLL.Reset();
            return RedirectToAction("ShowTickets");
        }
        
        protected override void OnException(ExceptionContext filterContext)
        {
            using (StreamWriter w = System.IO.File.AppendText(Server.MapPath(@"error.log")))
            {
                Log(filterContext.Exception.ToString(), w);
            }
             base.OnException(filterContext);
        }

        private void Log(string logMessage, TextWriter w)
        {
            w.WriteLine($"TicketController");
            w.Write("\r\nLog Entry: ");
            w.WriteLine($"{DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}\r\n");
            w.WriteLine($" {logMessage}\r\n");
            w.WriteLine("-----------------------------");
        }
    }
}


Webapps-Mappe1/Views/Shared/DeleteModal.cshtml
<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Bekreft sletting</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>Er du sikker på at du vil slette følgende?</p>
                <div class="text-danger" id="deleteName">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Lukk</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="btnModalDelete">Slett</button>
            </div>
        </div>
    </div>
</div>

Webapps-Mappe1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vy - @ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="~/Scripts/moderizr-2.8.3.js"></script>

</head>
<body style="padding:0">

    <nav class="navbar navbar-expand-lg navbar-dark" style="background:#3b3b3b">
        <a class="navbar-brand" href="@Url.Action("Index", "Ticket")">
            <img src="~/Content/Images/vy-white.svg" class="d-inline-block" height="30"/>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
                aria-controls="navbarContent" aria-expanded="false" aria-label="toggle-navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">

            <ul class="navbar-nav mr-auto">
                <li id="buyTicket" class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Ticket")">Kjøp billett</a>
                </li>
                <li id="showTickets" class="nav-item">
                    <a class="nav-link" href="@Url.Action("ShowTickets", "Ticket")">Se billetter</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li id="SignIn" class="nav-item ml-auto">
                    @{ 
                        var text = "Logg inn";
                        if (Session["SignIn"] != null && (bool)Session["SignIn"])
                        {
                            text = "Administrer";
                        }
                    }
                    <a class="nav-link" href="@Url.Action("Index", "Admin")">@text</a>
                </li>
            </ul>

        </div>

    </nav>
    <br/>
    @RenderBody()
        
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.no.min.js" charset="utf-8"></script>
    <script src="~/Scripts/moment.min.js"></script>
</body>
</html>