Webapps-Mappe1/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Webapps_Mappe1.Model;
using Webapps_Mappe1.BLL;
using System.IO;

namespace Webapps_Mappe1.Controllers
{
    public class StationController : Controller
    {
        StationBLL stationBLL;

        public StationController()
        {
            stationBLL = new StationBLL();
        }

        public StationController(StationBLL stationBLLStub)
        {
            stationBLL = stationBLLStub;
        }
            // GET: Station
        public ActionResult Index()
        {
            return View(stationBLL.GetAllStations());
        }

        public ActionResult CreateStation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateStation(Station station)
        {
            if (ModelState.IsValid)
            {
                if (stationBLL.CreateStation(station))
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }


        public void DeleteStation(int id)
        {
            stationBLL.DeleteStation(id);
        }

        public ActionResult EditStation(int id)
        {
            return View(stationBLL.GetStation(id));
        }


        [HttpPost]
        public ActionResult EditStation(int id, Station station)
        {
            if (ModelState.IsValid)
            {
                if (stationBLL.EditStation(id, station))
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        protected override void OnException(ExceptionContext filterContext)
        {
            using (StreamWriter w = System.IO.File.AppendText(Server.MapPath(@"error.log")))
            {
                Log(filterContext.Exception.ToString(), w);
            }
             base.OnException(filterContext);
        }

        private void Log(string logMessage, TextWriter w)
        {
            w.WriteLine($"StationController");
            w.Write("\r\nLog Entry: ");
            w.WriteLine($"{DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}\r\n");
            w.WriteLine($" {logMessage}\r\n");
            w.WriteLine("-----------------------------");
        }
    }
}

Webapps-Mappe1/Views/Station/CreateStation.cshtml
@model Webapps_Mappe1.Model.Station

@{
    ViewBag.Title = "CreateStation";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Opprett stasjon</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "hidden" } })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lagre" class="btn btn-primary" />
            </div>
        </div>
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Tilbake til listen", "Index")
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
    $("#CreatedBy").val('@Session["username"]');
    console.log('@Session["username"]', $('#LastModifiedBy'));

    })
</script>

Webapps-Mappe1/Views/Station/EditStation.cshtml
@model Webapps_Mappe1.Model.Station

@{
    ViewBag.Title = "Endre stasjon";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Endre stasjon</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.LastModifiedBy, new { htmlAttributes = new { @class = "hidden" } })
    </div>
</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lagre" class="btn btn-primary" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Tilbake til listen", "Index")
    </div>
</div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
    $("#LastModifiedBy").val('@Session["username"]');
    console.log('@Session["username"]', $('#LastModifiedBy'));

    })
</script>

Webapps-Mappe1/Views/Station/Index.cshtml
@model IEnumerable<Webapps_Mappe1.Model.Station>

@{
    ViewBag.Title = "Index";
}

<div class="ml-2">
    <h2>Stasjoner</h2>
    <p>
        @Html.ActionLink("Opprett stasjon", "CreateStation")
    </p>
    <input id="search" class="form-control mb-2" placeholder="Search" />
</div>


<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
            <th>@Html.DisplayNameFor(model => model.CreatedAt)</th>
            <th>@Html.DisplayNameFor(model => model.LastModifiedBy)</th>
            <th>@Html.DisplayNameFor(model => model.LastModifiedAt)</th>
        </tr>
    </thead>

    <tdoby>
        @foreach (var item in Model)
        {
            <tr class="row-@item.ID">
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
                <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
                <td>@Html.DisplayFor(modelItem => item.LastModifiedBy)</td>
                <td>@Html.DisplayFor(modelItem => item.LastModifiedAt)</td>
                <td>
                    <a href="@Url.Action("EditStation", "Station", new { id = item.ID })">Endre</a> |
                    <a href="#deleteModal" id="btnDelete"
                       data-name="@item.Name" data-id="@item.ID" data-toggle="modal" data-deleteModal="true">Slett</a>
                </td>
            </tr>
        }
    </tdoby>
</table>
@Html.Partial("DeleteModal")


<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript">

    function removeRowWithId(id) {
        console.log($(`.row-${id}`), id);
        $(`.row-${id}`).remove();
    }

    $(document).ready(function () {
        $('a[data-deleteModal=true]').click(function () {

            var data_name = $(this).data('name');
            var data_id = $(this).data('id');

            $('#deleteName').html(data_name);

            $('#btnModalDelete').click(function () {
                 $.ajax({
                    url: '@Url.Action("DeleteStation", "Station")',
                    data: { id: data_id },
                    success: function () {
                        removeRowWithId(data_id);
                }
                });
            })
        })
        $('#search').on('keyup paste', function () {
            $('tbody tr').addClass('hidden')
                .each(function (i, el) {
                    let search = $('#search').val().toLowerCase();
                    console.log(search);
                    console.log($(el).children());
                    if ($(el).children()[0].innerHTML.toLowerCase().startsWith(search)) {
                        $(el).removeClass('hidden');
                    }
                });
        });
    });
</script>