Webapps-Mappe1/Controllers/AdminController.cs
using System;
using System.Web.Mvc;

using Webapps_Mappe1.Model;
using Webapps_Mappe1.BLL;
using System.IO;

namespace Webapps_Mappe1.Controllers
{
    public class AdminController : Controller
    {
        StationBLL stationBLL;
        DepartureBLL departureBLL;
        PriceBLL priceBLL;
        AdminBLL userBLL;

        public AdminController()
        {
            stationBLL = new StationBLL();
            departureBLL = new DepartureBLL();
            priceBLL = new PriceBLL();
            userBLL = new AdminBLL();
        }

        public AdminController(PriceBLL priceBLLStub)
        {
            priceBLL = priceBLLStub;
        }

        public ActionResult Index()
        {
            if (userBLL.CheckAdminExists())
            {
                userBLL.createAdmin();
                Session["SignIn"] = false;
            }


            if (Session["SignIn"] == null || !(bool)Session["SignIn"])
            {
                Session["SignIn"] = false;
                ViewBag.Signedin = false;
            }
            else
            {
                ViewBag.Signedin = (bool)Session["SignIn"];
                return RedirectToAction("AdminPage");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Index(Admin inUser)
        {
            DBUser foundUser = userBLL.UserInDB(inUser);
            if (foundUser != null)
            {
                Session["SignIn"] = true;
                ViewBag.Signedin = inUser.Name;
                Session["username"] = inUser.Name;
                return RedirectToAction("AdminPage");
            }
            else
            {
                Session["SignIn"] = false;
                ViewBag.Signedin = "Else";
                Session["username"] = "Automatisk";
                return View();
            }
        }


        public ActionResult AdminPage()
        {
            if (Session["SignIn"] != null)
            {
                bool SignIn = (bool)Session["SignIn"];
                if (SignIn)
                {
                    return View();
                }
            }
            return RedirectToAction("Index");
        }


        protected override void OnException(ExceptionContext filterContext)
        {
            using (StreamWriter w = System.IO.File.AppendText(Server.MapPath(@"error.log")))
            {
                Log(filterContext.Exception.ToString(), w);
            }
            base.OnException(filterContext);
        }

        private void Log(string logMessage, TextWriter w)
        {
            w.WriteLine($"AdminController");
            w.Write("\r\nLog Entry: ");
            w.WriteLine($"{DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}\r\n");
            w.WriteLine($" {logMessage}\r\n");
            w.WriteLine("-----------------------------");
        }
    }
}

Webapps-Mappe1/Controllers/DepartureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Webapps_Mappe1.Model;
using Webapps_Mappe1.BLL;
using System.IO;

namespace Webapps_Mappe1.Controllers
{
    public class DepartureController : Controller
    {
        DepartureBLL departureBLL;

        public DepartureController()
        {
            departureBLL = new DepartureBLL();
        }

        public DepartureController(DepartureBLL departureBLLStub)
        {
            departureBLL = departureBLLStub;

        }

        
        // GET: Departure
        public ActionResult Index()
        {
            return View(departureBLL.GetAllDepartures());
        }

        public ActionResult Reset()
        {
            departureBLL.Reset();
            return RedirectToAction("Station/Index");
        }

        public ActionResult EditDeparture(int id)
        {
            return View(departureBLL.GetDeparture(id));
        }

        [HttpPost]
        public ActionResult EditDeparture(int id, Departure departure)
        {
            if (ModelState.IsValid)
            {
                if (departureBLL.EditDeparture(id, departure))
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public void DeleteDeparture(int id)
        {
            departureBLL.DeleteDeparture(id);
        }

        public ActionResult CreateDeparture()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateDeparture(DepartureModel departure)
        {

            /*   if (Session["SignIn"] != null) //Har den her også selv om det ikke er en egen side, vet ikke om det er nødvendig
               {
                   bool SignIn = (bool)Session["SignIn"];
                   if (!SignIn)
                   {
                       return RedirectToAction("Index"); skal redirecte til admin index
                   }
               }*/
            if (ModelState.IsValid)
            {
                if (departureBLL.CreateDeparture(departure))
                    return RedirectToAction("Index");
            }
            return View();
        }
        protected override void OnException(ExceptionContext filterContext)
        {
            using (StreamWriter w = System.IO.File.AppendText(Server.MapPath(@"error.log")))
            {
                Log(filterContext.Exception.ToString(), w);
            }
            base.OnException(filterContext);
        }

        private void Log(string logMessage, TextWriter w)
        {
            w.WriteLine($"DepartureController");
            w.Write("\r\nLog Entry: ");
            w.WriteLine($"{DateTime.Now.ToLongDateString()} {DateTime.Now.ToLongTimeString()}\r\n");
            w.WriteLine($" {logMessage}\r\n");
            w.WriteLine("-----------------------------");
        }
    }
}

Webapps-Mappe1/Views/Departure/CreateDeparture.cshtml
@model Webapps_Mappe1.Model.DepartureModel
@using Webapps_Mappe1.Model
@using Webapps_Mappe1.BLL

@{
    ViewBag.Title = "Opprett avgang";
}

@{
    List<SelectListItem> stationList = new List<SelectListItem>();
    var stationBLL = new StationBLL();
    var stations = stationBLL.GetAllStations();

    foreach (Station s in stations)
    {
        stationList.Add(new SelectListItem
        {
            Text = s.Name,
            Value = s.Name
        });
    }
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h2>Opprett avgang</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="d-flex">
                    <input type="number" class="form-control col-1" placeholder="00" id="hours" max="23" />
                    <span class="m-1" style="font-size: 2rem; margin-top:-0.5rem!important">:</span>
                    <input type="number" class="form-control col-1" placeholder="00" id="minutes" max="59" />
                </div>
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control hidden" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.StartStation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StartStation, stationList, "Velg stasjon", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StartStation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndStation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EndStation, stationList, "Velg stasjon", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EndStation, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "hidden" } })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Opprett" class="btn btn-primary" id="btnConfirm" />
            </div>
        </div>
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Tilbake til listen", "Index")
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    let times = $('#StartTime').val().split(':');
    $('#hours').val(times[0]);
    $('#minutes').val(times[1]);
</script>

<script>
    $(document).ready(function () {
    $("#CreatedBy").val('@Session["username"]');
    console.log('@Session["username"]', $('#CreatedBy'));

    })
</script>

Webapps-Mappe1/Views/Departure/EditDeparture.cshtml
@model Webapps_Mappe1.Model.Departure

@{
    ViewBag.Title = "Endre avgang";
}

<head>

</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Endre avgang</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="control-label col-md-2">
            Ny tid
        </div>

        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control hidden" } })
            <div class="d-flex">
                <input type="number" class="form-control col-1" placeholder="00" id="hours" max="23" />
                <span class="m-1" style="font-size: 2rem; margin-top:-0.5rem!important">:</span>
                <input type="number" class="form-control col-1" placeholder="00" id="minutes" max="59" />
            </div>
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.LastModifiedBy, new { htmlAttributes = new { @class = "hidden" } })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Lagre" class="btn btn-primary" id="btnConfirm" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Tilbake til listen", "Index")
    </div>
</div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    let times = $('#StartTime').val().split(':');
    $('#hours').val(times[0]);
    $('#minutes').val(times[1]);
</script>

<script>
    $(document).ready(function () {
    $("#LastModifiedBy").val('@Session["username"]');
    console.log('@Session["username"]', $('#LastModifiedBy'));

    })
</script>

Webapps-Mappe1/Views/Departure/Index.cshtml
@model IEnumerable<Webapps_Mappe1.Model.Departure>

@{
    ViewBag.Title = "ShowDepartures";
}

<div class="ml-2">
    <h2>Avganger</h2>
    <p>
        @Html.ActionLink("Opprett avgang", "CreateDeparture")
    </p>
    <input id="search" class="form-control mb-2" placeholder="Search" />
</div>


<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.StartTime)</th>
            <th>@Html.DisplayNameFor(model => model.StartStation)</th>
            <th>@Html.DisplayNameFor(model => model.EndStation)</th>
            <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
            <th>@Html.DisplayNameFor(model => model.CreatedAt)</th>
            <th>@Html.DisplayNameFor(model => model.LastModifiedBy)</th>
            <th>@Html.DisplayNameFor(model => model.LastModifiedAt)</th>
            <th>Rediger</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.StartTime)</td>
            <td>@Html.DisplayFor(modelItem => item.StartStation.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.EndStation.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
            <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
            <td>@Html.DisplayFor(modelItem => item.LastModifiedBy)</td>
            <td>@Html.DisplayFor(modelItem => item.LastModifiedAt)</td>
            <td>
                <a href="@Url.Action("EditDeparture", "Admin", new { id = item.ID })">Endre tid</a> |
                <a href="#deleteModal" id="btnDelete" class="text-danger" data-toggle="modal" data-deleteModal="true"
                   data-name="@item.StartTime | @item.StartStation.Name → @item.EndStation.Name" data-id="@item.ID">Slett</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@Html.Partial("DeleteModal")



<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript">
    function removeRowWithId(id) {
        console.log($(`.row-${id}`), id);
        $(`.row-${id}`).remove();
    }

        $(document).ready(function () {
            $('a[data-deleteModal=true]').click(function () {

                var data_name = $(this).data('name');
                var data_id = $(this).data('id');

                console.log(data_name);
                console.log(data_id);

                $('#deleteName').html(data_name);

                $('#btnModalDelete').click(function () {
                    $.ajax({
                        url: '@Url.Action("DeleteDeparture", "Departure")',
                        data: { id: data_id },
                        success: function () {
                            removeRowWithId(data_id);
                        }
                    });
                })
            })


            $('#search').on('keyup paste', function () {
                $('tbody tr').addClass('hidden')
                    .each(function (i, el) {
                        let search = $('#search').val().toLowerCase().split(',');
                        let from = search[0];
                        let to = search[1];
                        if ($(el).children()[1].innerHTML.toLowerCase().startsWith(from)) {
                            if (to !== undefined && to !== "") {
                                if ($(el).children()[2].innerHTML.toLowerCase().startsWith(to.trim())) {
                                    $(el).removeClass('hidden');
                                }
                            } else {
                                $(el).removeClass('hidden');
                            }
                        }
                });
            });
        });
</script>